# Generated by Django 2.0 on 2018-10-14 20:04

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180410_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
